Bowling object
Aseiide/ruby-practices pull request #6
Opened 2021-08-02 08:34 UTC by Aseiide

2021-08-08 02:52 UTC, u1tnk requested changes

2021-08-08 02:52 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    # irb(#<Game:0x00007fd1a2942ca0>):001:0> frames
これはメモですかね？
不要なコメントは消しましょう。

2021-08-08 02:52 UTC, u1tnk commented on 07.bowling_object/game.rb
> +      if frame.first == STRIKE
細かいですが、sfhit(2)する前に分岐した方がスッキリすると思います。

2021-08-08 02:52 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    @frames = separate_frames(argv)
`@frames`という変数名なので、中身は `Frame`クラスのインスタンス配列と予想しましたた違うようです。
できれば  `Frame`クラスのインスタンス配列 とした方が良いと思いますが、できなくても `frames`では誤解をまねくので名前は変えた方が良いですね。

2021-08-08 02:52 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  attr_reader :first_shot, :second_shot, :third_shot
外部からアクセスされない場合は attr_readerは定義しない方が良いです。無駄なコードを減らす、カプセル化の観点が理由です。

2021-08-08 02:52 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +    @first_shot = Shot.new(first_shot)
まあ細かいのでどっちでも良いですが、Gameと合わせて `@shots`の形で持っても良いですね。

2021-08-08 02:52 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  def not_last_frame?(index)
メソッドで `not_` を持つのは混乱しがちなのでやらない方が良いですね。 (頻出ならやる事もあります)
`last_frame?`にして利用側で unlessにしたり、`!`を付けたりした方が良いと思います。

2021-08-08 02:52 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +      strike_score(index, next_frame_marks, after_next_frame_marks)
`strike_score`/`spare_score`は外部から呼ばれないですよね？そうなると privateを付けた方が良いですね。
クラスの内容を修正する必要があったときに、外部から呼ばれている限定できるのはとても大事なんです。

2021-08-08 02:52 UTC, u1tnk commented on 07.bowling_object/game.rb
> +    @frames = separate_frames(argv)
Frameの引数を見ると marksなので、 名前を変えるとするなら配列の配列だから `marks_list`とかですかね。微妙な名前ではあると思います 😅

2021-08-17 07:57 UTC, Aseiide commented on 07.bowling_object/game.rb
> +    # irb(#<Game:0x00007fd1a2942ca0>):001:0> frames
セルフレビューができていませんでした。削除しました

2021-08-17 08:21 UTC, Aseiide reviewed
返答遅くなってしまいました。

2021-08-17 08:21 UTC, Aseiide commented on 07.bowling_object/frame.rb
> +      strike_score(index, next_frame_marks, after_next_frame_marks)
ご指摘の話は、質問タイムでも聞いたことがありました。
「外部から呼び出す必要があったときにprivateから外せば良い」と。

`spare?` `strike?`も外部から呼ばれていないのでprivateに入れました

2021-08-17 08:21 UTC, Aseiide commented on 07.bowling_object/frame.rb
> +  attr_reader :first_shot, :second_shot, :third_shot
こちら、まだ修正できていないです、、！

L26でアクセスしているので`attr_reader`は必要かなと思いました。
L8を削除したところ、プログラム自体動かなくなってしまいまして、どうしたらよいのか分からなかったです、、

2021-08-17 08:21 UTC, Aseiide commented on 07.bowling_object/game.rb
> +      if frame.first == STRIKE
こちらもまだ修正できていません、、！
手元で様々試してみたのですが、どういう方向で修正すればよいでしょうか?

2021-08-17 13:05 UTC, u1tnk requested changes
修正方針についてコメントつけました。

2021-08-17 13:05 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  attr_reader :first_shot, :second_shot, :third_shot
なるほど。
L26の方も修正して `@first_shot`でアクセスすれば良いですよ。
`@` が付いてない方がスッキリして読みやすいのは確かですが、この場合は `@`がある事で「このクラスのインスタンス変数」である事がはっきりしてデータの居場所が分かりやすくなります。
rubyは「読みやすさ」を重視する文化があって、シンプルに書ける事も大切ではありますが、オブジェクト指向的にカプセル化の穴になってよくないですし、データの場所が分かる事も「読みやすさ」につながります。
何を重視すべきか難しいとは思いますが、経験を積んでいけば分かるようになりますので 💪

2021-08-17 13:05 UTC, u1tnk commented on 07.bowling_object/game.rb
> +      if frame.first == STRIKE
テクニックの話なので書いちゃいますね。

```
    9.times do
      if frame.first == STRIKE
        frames << [shots.shift, 0]
        next
      end
...
```
を先にやっちゃう感じですね。 `next` は次のループに進みます。

元の処理だと、shotsを2個減らして1個戻して…と行ったりきたりしますが、先に判定しておくと減らすだけなので処理がシンプルになります。

2021-08-19 14:29 UTC, Aseiide reviewed
修正、コメントしました！宜しくお願い致します。

2021-08-19 14:29 UTC, Aseiide commented on 07.bowling_object/game.rb
> +                end
このように修正してみました！

2021-08-19 14:29 UTC, Aseiide commented on 07.bowling_object/frame.rb
> +    @first_shot.score + next_frame.@first_shot.score + bonus_point
このコードは動かないです、、！
ご指摘に沿って修正していたのですが、ここで`first_shot` `second_shot` `third_shot` にアクセスしていました。
なので、`attr_reader`必要かなと。元のコードのままで良いのでは?と思ったのですが、いかがでしょう？

参考までに、このコードで実行したときの結果も貼っておきますね〜。

![スクリーンショット 2021-08-19 23 28 45](https://user-images.githubusercontent.com/45246171/130086731-310eef57-cf39-466d-b307-41548389d32a.png)

2021-08-20 01:28 UTC, u1tnk requested changes

2021-08-20 01:28 UTC, u1tnk commented on 07.bowling_object/game.rb
> +  attr_reader :marks_list
指摘漏れてましたが、この attr_readerも不要だと思います。

2021-08-20 01:28 UTC, u1tnk commented on 07.bowling_object/frame.rb
> +  # attr_reader :first_shot, :second_shot, :third_shot
gitに履歴は残るのでコメントアウトは残さずに完全に削除しましょう。

2021-08-20 01:28 UTC, u1tnk commented on 07.bowling_object/game.rb
> +                end
良くなりましたね 👍

2021-08-24 06:39 UTC, Aseiide commented on 07.bowling_object/game.rb
> +  attr_reader :marks_list
修正して、インスタンス変数からアクセスするようにしました！

2021-09-16 07:55 UTC, u1tnk requested changes
一点作業漏れっぽい所があったので修正お願いします 🙏

2021-09-16 07:55 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    bonus_point = next_frame.shots[0].score != STRIKE || index == 8 ? next_frame.shots[1].score : after_next_frame.shots[0].score
` != STRIKE`
が残っていますね。せっかく `Shot#strike?` があるのでそちらに統一しましょう。

2021-09-16 08:04 UTC, Aseiide commented on 07.bowling_object/lib/frame.rb
> +    bonus_point = next_frame.shots[0].strike? == false || index == 8 ? next_frame.shots[1].score : after_next_frame.shots[0].score
修正しました！

2021-09-16 08:23 UTC, u1tnk requested changes

2021-09-16 08:23 UTC, u1tnk commented on 07.bowling_object/lib/frame.rb
> +    bonus_point = next_frame.shots[0].strike? == false || index == 8 ? next_frame.shots[1].score : after_next_frame.shots[0].score
booleanの値に `== false`と比較するのは混乱するだけなので、 `xxx?`だけと `!xxx?` の二種類にしましょう。

2021-09-16 08:24 UTC, u1tnk approved these changes
もう修正方針が明らかな指摘のみなのでOKとします :ok_wo

2021-09-17 05:02 UTC, Aseiide commented on 07.bowling_object/lib/frame.rb
> +    bonus_point = !next_frame.shots[0].strike? || index == 8 ? next_frame.shots[1].score : after_next_frame.shots[0].score
`!.strike?`という、メソッドの前にしか`!`置けないと思っていました。
こういう書き方できるんですね。

2021-09-21 08:05 UTC, merged